module.exports = {
    "students" : [
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ODM1YjE0ZjcwZDA0ZDI5ZDE3OGRmNzFhOTNiZjA5NjI3NmJkNWUwNDpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTgzNjE1MTMzMjM4OTI1OSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9YjdkMDBmNWZlMTc1Mjg2YTNkOTkxYzExMmNkZTU2ZjgxMTgxNmExYTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTQxMzM5MjgxNjYxNjk4MiZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [
                {
                    "osVersion" : "10.0",
                    "osName" : "windows",
                    "browserVersion" : "77.0.3865.120",
                    "browserName" : "chrome",
                    "deviceType" : "web",
                    "dcAppReleaseVersion" : null,
                    "loggedInTime" : 1586771011498.0,
                    "loggedOutTime" : 1586773384916.0
                }
            ],
            "accessToken" : null,
            "socketId" : "JKpagyYEWWgCyUX6AAAC",
            "deviceType" : "web",
            "isAway" : true,
            "loggedIn" : true,
            "joined" : true,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "photoUri" : "https://myguitarlessons.co.uk/wp-content/uploads/formidable/249538_137513649658546_544597_n-190x190.jpg",
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student1",
            "id" : "USTUDENT1",
            "joinedTime" : 1586771012651.0
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ZjJkYTY3OTc0ZjFhN2U0MTQwZDc3NDAyOTE0N2Y1M2RlOTdjNzg2MzpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuOTUzMTA2MzE5NTM4MTE0OSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9MGQ2YWZiNzQ3YWYzMDc5YmZjNDExMTg3NjkwOWRmNjYwMzFhYTZmYTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNzAwODYyNDU1NDUyODU5MSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [
                {
                    "osVersion" : "10.0",
                    "osName" : "windows",
                    "browserVersion" : "77.0.3865.120",
                    "browserName" : "chrome",
                    "deviceType" : "web",
                    "dcAppReleaseVersion" : null,
                    "loggedInTime" : 1586771060819.0,
                    "loggedOutTime" : 1586773384437.0
                }
            ],
            "accessToken" : null,
            "socketId" : "l9Qr45zuOCV4V9u7AAAD",
            "deviceType" : "web",
            "isAway" : false,
            "loggedIn" : true,
            "joined" : true,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "photoUri" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLKUuH6rWnUE0m16ven2nkQcyw-25r03g9iXdWX5UPz-sS7XEdRA",
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student2",
            "id" : "USTUDENT2",
            "joinedTime" : 1586771061988.0
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ZDRlZDNjNGIzN2NmNjlhNmIyNTA1MTBjODdkYWRlMWQxNTQ2NTJlNzpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTc1NTAyNzU2MTMwMDk4MyZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9YjMwOThjYzFjZjllNTAyM2M0YWYwYWYxOTNhNGUxNmZkMDQ4YWQ5NTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTU0NzcyNTM0MzUxNTU5MyZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [],
            "accessToken" : null,
            "socketId" : null,
            "deviceType" : null,
            "isAway" : false,
            "loggedIn" : false,
            "joined" : false,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student3",
            "id" : "USTUDENT3"
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ZjE5MTZlYjkxMjgzY2ExOTc1MDRhOGZhMDMzZmNlMjRhYTEzNDQ3NzpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTMxMTg5MTQ4NDMwNzgyNSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9YzkzM2NjZmY0MmIwMmI5NTY1M2NjMmVmYzMxMTE1YjBkMTliMGM4YjpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNzExODYzNDY2NDc5MTMxNSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [],
            "accessToken" : null,
            "socketId" : null,
            "deviceType" : null,
            "isAway" : false,
            "loggedIn" : false,
            "joined" : false,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student4",
            "id" : "USTUDENT4"
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9YmYxMmUzMTZmZjdjM2YyYWQyYWViYzU0YjczYzIzYjM3MTljZDllMjpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTQ0MTUyNTg2MDU4NDI0OSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9YjAyOWU1NDEwMzliMDk1OGFmMWNjYmI5ODJlODhkYTk0OTJiODEzNTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuODM5OTg2ODkyNTEzMTYyOCZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [],
            "accessToken" : null,
            "socketId" : null,
            "deviceType" : null,
            "isAway" : false,
            "loggedIn" : false,
            "joined" : false,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student5",
            "id" : "USTUDENT5"
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9NmY1OWQ2N2Y2Yzc3MjdmNTUyMDNlY2UwYWNjNGUwNjc0NTk3NTBiMTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNzEyNTA3NjM2NzEwMTE3NyZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9NjBhODM3MDhmOTM2ZTg5Y2E0ZTk4MTdkYjNhMThiZmUwY2MyNzVjNzpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuMDU2MzMxNDQzODYzNzQ5ODg2JnJvbGU9cHVibGlzaGVyJmV4cGlyZV90aW1lPTE1ODY4NTY5NjcmaW5pdGlhbF9sYXlvdXRfY2xhc3NfbGlzdD0=",
            "loginDetails" : [],
            "accessToken" : null,
            "socketId" : null,
            "deviceType" : null,
            "isAway" : false,
            "loggedIn" : false,
            "joined" : false,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student6",
            "id" : "USTUDENT6"
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ZDliODlkOTdlZDQ0NzI2YzU5ZDQzOThjMDg0MGFjMzY4ZDM3OGY5NTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNDIzNDMzMjI2MzQwMTM2MzYmcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTU4Njg1Njk2NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ZmQwYmU0NzE3Mzg5MTg3NzY2NTZkMGE3ZDRjNGUxZWUxZTIxMzYxNTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuNTI1NTgyNTY0MTIyNDM3OSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [],
            "accessToken" : null,
            "socketId" : null,
            "deviceType" : null,
            "isAway" : false,
            "loggedIn" : false,
            "joined" : false,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student7",
            "id" : "USTUDENT7"
        },
        {
            "role" : "student",
            "expelled" : false,
            "handRised" : false,
            "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9ZmM1N2FiZjQ1YTFkNmNkNmU5YjY0Y2ZhNDU0ZTJlNGM2Y2U1OTA1MTpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuMzEzNjgxMzkyMjU4NjY1NjUmcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTU4Njg1Njk2NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==",
            "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9MTdkNWMxMDhhYzZmMDNmMDA3NmZlZjlmMTgyYzAwMzU3YWRlZmE3YjpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuOTk1ODAwOTgzNTk2NTI4MiZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
            "loginDetails" : [],
            "accessToken" : null,
            "socketId" : null,
            "deviceType" : null,
            "isAway" : false,
            "loggedIn" : false,
            "joined" : false,
            "online" : false,
            "camHardMuted" : false,
            "micHardMuted" : false,
            "camAvailable" : true,
            "camEnabled" : true,
            "micAvailable" : true,
            "micEnabled" : true,
            "gender" : "Male",
            "lastName" : "",
            "firstName" : "Student8",
            "id" : "USTUDENT8"
        }
    ],
    "teacher" : {
        "role" : "teacher",
        "otNetworkTestToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9MGIwMWYzNjRhNTJlMDFmMjAxYzQ4NjY2ZDY5NGI5MDE2ZmQ0NDAyMDpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk5qQTVOMzVaZDJOdFJXNXlhWFJpTTNaaGJEQmFRVGhTYVdOcVJ6Ri1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuMzY1NDExODkyMjQwNjM3NSZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTg2ODU2OTY3JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9",
        "otToken" : "T1==cGFydG5lcl9pZD00NTYzNzY2MiZzaWc9N2FjMTI1ZmIwN2Y1OGE2OWJjY2FjYjIyMGE5NDExODUxMGJhOWFjZDpzZXNzaW9uX2lkPTFfTVg0ME5UWXpOelkyTW41LU1UVTROamMzTURVMk56QTRPSDQ0Vms0cmVtazVWVllyTlVSbVZteFljMDVVZUVObFFXWi1mZyZjcmVhdGVfdGltZT0xNTg2NzcwNTY3Jm5vbmNlPTAuMDM2OTM2Njg2NTQ4NTg5Mzkmcm9sZT1wdWJsaXNoZXImZXhwaXJlX3RpbWU9MTU4Njg1Njk2NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==",
        "loginDetails" : [
            {
                "osVersion" : "10.15.3",
                "osName" : "mac os x",
                "browserVersion" : "80.0.3987.163",
                "browserName" : "chrome",
                "deviceType" : "web",
                "dcAppReleaseVersion" : null,
                "loggedInTime" : 1586770593170.0,
                "loggedOutTime" : 1586771237651.0
            }
        ],
        "accessToken" : null,
        "socketId" : "4vzur5G3wYx8js84AAAE",
        "deviceType" : "web",
        "isAway" : false,
        "loggedIn" : true,
        "joined" : true,
        "online" : false,
        "camHardMuted" : false,
        "micHardMuted" : false,
        "camAvailable" : true,
        "camEnabled" : true,
        "micAvailable" : true,
        "micEnabled" : true,
        "gender" : "Male",
        "photoUri" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpv6GDhy7F9EJe63buZll5mlccPSHhay3bOaT9LhHCH3FImUb9Pw",
        "lastName" : "",
        "firstName" : "Teacher",
        "id" : "UTEACHER",
        "joinedTime" : 1586770594438.0,
        "handRised" : false
    },
    "session" : {
        "networkTestSession" : {
            "otSessionId" : "1_MX40NTYzNzY2Mn5-MTU4Njc3MDU2NjA5N35Zd2NtRW5yaXRiM3ZhbDBaQThSaWNqRzF-fg",
            "otKey" : "45637662"
        },
        "otSessionId" : "1_MX40NTYzNzY2Mn5-MTU4Njc3MDU2NzA4OH44Vk4remk5VVYrNURmVmxYc05UeENlQWZ-fg",
        "otKey" : "45637662",
        "tsEnded" : null,
        "ended" : false,
        "waitTime" : 0,
        "timeLeft" : 777,
        "endTime" : 1586774162713.0,
        "startTime" : 1586770562713.0,
        "slot" : "60"
    },
    "chatData" : {
        "notificationCount" : {
            "USTUDENT8" : {
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT7" : {
                "USTUDENT8" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT6" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT5" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT4" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT3" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT2" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT1" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "USTUDENT1" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "UTEACHER" : 0,
                "EVERYONE" : 0
            },
            "UTEACHER" : {
                "USTUDENT8" : 0,
                "USTUDENT7" : 0,
                "USTUDENT6" : 0,
                "USTUDENT5" : 0,
                "USTUDENT4" : 0,
                "USTUDENT3" : 0,
                "USTUDENT2" : 0,
                "USTUDENT1" : 0,
                "EVERYONE" : 0
            }
        },
        "privateChat" : {
            "USTUDENT8" : [],
            "USTUDENT7" : [],
            "USTUDENT6" : [],
            "USTUDENT5" : [],
            "USTUDENT4" : [],
            "USTUDENT3" : [],
            "USTUDENT2" : [],
            "USTUDENT1" : [],
            "UTEACHER" : []
        },
        "publicChat" : []
    },
    "wbData" : {
        "externalFiles" : [],
        "breakouts" : {
            "rooms" : [
                {
                    "users" : [],
                    "title" : "Room 1",
                    "id" : 0
                },
                {
                    "users" : [],
                    "title" : "Room 2",
                    "id" : 1
                },
                {
                    "users" : [],
                    "title" : "Room 3",
                    "id" : 2
                },
                {
                    "users" : [],
                    "title" : "Room 4",
                    "id" : 3
                }
            ],
            "remainingTime" : null,
            "teacherRoom" : null,
            "startTime" : null,
            "timeSlot" : 0,
            "isActive" : false,
            "maxLength" : 4,
            "minLength" : 2
        },
        "currentPrivilege" : {
            "role" : "teacher",
            "id" : "UTEACHER"
        },
        "pointer" : {
            "isActive" : false,
            "annotation" : {
                "ow" : 0,
                "y" : 0,
                "x" : 0
            },
            "slideIndex" : 0,
            "boardIndex" : 0
        },
        "boards" : [
            {
                "annotations" : [],
                "label" : "Whiteboard",
                "mount" : null,
                "type" : "BLANK",
                "index" : 0
            }
        ],
        "activeBoard" : 0
    },
    "lastMsgId" : 41,
    "activeScreen" : "whiteboard"
};
